name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run:  run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ Repository cloned!"
      - run: echo "ğŸ§ª Workflow ready to test code."
      - name: List files in repository
        run: ls ${{ github.workspace }}
      - run: echo "ğŸ Job status: ${{ job.status }}"
